apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  DBNAME: {{ .Values.environment.dbname }}
  DBUSER: {{ .Values.environment.dbuser }}
  DBPASS: {{ .Values.environment.dbpass }}
  DBHOST: {{ .Values.environment.dbhost }}
  DBPORT: "{{ .Values.environment.dbport }}"
